stages:
  - build
  - deploy

variables:
    BUCKET_NAME: zekoder-zestudio-mfe-webcomponents

dev build:
  stage: build
  image: node:current-alpine3.16
  before_script:
    - npm install
  script:
    - npm run build
  only:
    - dev
  artifacts:
    paths:
      - dist
  
dev deploy:
    stage: deploy
    image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
    script:
      - aws s3 cp dist/ s3://${BUCKET_NAME}/ --recursive
    only:
      - dev
