stages:
  - build
  - deploy

variables:
    BUCKET_NAME: zekoder-zestudio-mfe-webcomponents

dev build:
  stage: build
  image: node:16.17-alpine3.15
  before_script:
    - npm install
  script:
    - npm run build
  only:
    - dev
    - merge_requests
  artifacts:
    paths:
      - dist
  
dev deploy:
    stage: deploy
    image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
    script:
      - aws s3 sync dist/ s3://${BUCKET_NAME}/    
    only:
      - dev
      - merge_requests
